export const SCAN_CODE_LOGIN = 'SCAN_CODE_LOGIN'
export const CONFIRM_LOGIN = 'CONFIRM_LOGIN'
export const SAVE_USER_INFO = 'SAVE_USER_INFO'
export const VALID_ONE = 'VALID_ONE'
export const USER_SORT = 'USER_SORT'
export const SORT_LIST = 'SORT_LIST'
